# Generated by Django 5.2.7 on 2025-10-09 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('queue_manage', 'Queue Management'), ('token_issue', 'Token Issue'), ('patient_call', 'Patient Call'), ('consultation_start', 'Consultation Start'), ('consultation_end', 'Consultation End')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_patients', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('total_cancelled', models.IntegerField(default=0)),
                ('total_missed', models.IntegerField(default=0)),
                ('average_wait_time', models.FloatField(default=0.0, help_text='Average wait time in minutes')),
                ('average_consultation_time', models.FloatField(default=0.0, help_text='Average consultation time in minutes')),
                ('peak_hour_start', models.TimeField(blank=True, null=True)),
                ('peak_hour_end', models.TimeField(blank=True, null=True)),
                ('patient_satisfaction_avg', models.FloatField(default=0.0, help_text='Average satisfaction rating')),
                ('doctors_on_duty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('general', 'General Settings'), ('notification', 'Notification Settings'), ('queue', 'Queue Settings'), ('analytics', 'Analytics Settings')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
