# Generated by Django 5.2.7 on 2025-10-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this admin can manage', to='patients.department'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentanalytics',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.department'),
        ),
        migrations.AlterUniqueTogether(
            name='systemconfiguration',
            unique_together={('config_type', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentanalytics',
            unique_together={('department', 'date')},
        ),
    ]
