# Generated by Django 5.2.7 on 2025-10-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When patient arrived and scanned QR', null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='booked_at',
            field=models.DateTimeField(blank=True, help_text='When booking was made online', null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='booking_date',
            field=models.DateField(blank=True, help_text='Date for which booking was made', null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='booking_time_slot',
            field=models.CharField(blank=True, help_text='Preferred time slot', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='is_online_booking',
            field=models.BooleanField(default=False, help_text='True if booked online from home'),
        ),
        migrations.AddField(
            model_name='queue',
            name='preferred_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor requested by patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_bookings', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='queue',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Unique QR code for this booking', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked Online'), ('arrived', 'Arrived at Hospital'), ('waiting', 'Waiting'), ('called', 'Called'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('late_entry', 'Late Entry'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
