# Generated by Django 5.2.7 on 2025-10-09 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('token_issued', 'Token Issued'), ('turn_approaching', 'Turn Approaching'), ('turn_ready', 'Turn Ready'), ('missed_turn', 'Missed Turn'), ('consultation_complete', 'Consultation Complete'), ('appointment_reminder', 'Appointment Reminder')], max_length=30)),
                ('sms_template', models.TextField(help_text='SMS template with placeholders like {name}, {token_number}, etc.')),
                ('whatsapp_template', models.TextField(blank=True, help_text='WhatsApp template')),
                ('email_template', models.TextField(blank=True, help_text='Email template')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('notify_on_token_issue', models.BooleanField(default=True)),
                ('notify_when_turn_approaches', models.BooleanField(default=True)),
                ('notify_minutes_before', models.IntegerField(default=15, help_text='Minutes before turn to send notification')),
                ('notify_on_turn_ready', models.BooleanField(default=True)),
                ('notify_on_missed_turn', models.BooleanField(default=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification')], max_length=20)),
                ('message', models.TextField()),
                ('recipient', models.CharField(help_text='Phone number, email, or device token', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('queue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.queue')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
            ],
        ),
    ]
